language: java
jdk:
  - openjdk8
sudo: false # faster builds
script: 
  - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
before_install:
  - chmod +x mvnw
after_success:
  - bash <(curl -s https://codecov.io/bash)