version: 0.0
os: linux
files:
- source: target/demo-0.0.1-SNAPSHOT.jar
  destination: /tmp
permissions:
- object: /tmp
  pattern: "*.jar"
  owner: ec2-user
  group: ec2-user
hooks:
  ApplicationStart:
  - location: scripts/deploy.sh
    timeout: 180
#  ValidateService:
#  - location: healthCheck.sh
#    timeout: 60
#    runas: ec2-user